# Generated by Django 4.0.6 on 2022-07-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_teacher_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='qualification',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
