# Generated by Django 4.0.6 on 2022-07-29 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_course_featured_img_course_techs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='techs',
            field=models.TextField(null=True),
        ),
    ]
