# Generated by Django 4.0.6 on 2022-07-30 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_student_options_chapter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='Course',
            new_name='course',
        ),
    ]
