# Generated by Django 4.0.6 on 2022-08-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_teacher_detail_alter_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='detail',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
