# Generated by Django 4.0.6 on 2022-08-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_teacher_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='detail',
            field=models.TextField(null=True),
        ),
    ]
