# Generated by Django 4.0.6 on 2022-08-03 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_teacher_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='interested_category',
            new_name='interested_categories',
        ),
    ]
