# Generated by Django 4.0.6 on 2022-08-03 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_rename_interested_category_student_interested_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='qualification',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mobile_no',
        ),
    ]
