# Generated by Django 4.0.6 on 2022-08-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('query', models.TextField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '7. Contact',
            },
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name_plural': '7. Faq'},
        ),
    ]
