# Generated by Django 4.0.6 on 2022-08-07 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_contact_alter_faq_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': '8. Contact'},
        ),
    ]
