# Generated by Django 4.0.6 on 2022-08-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_contact_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='otp_digit',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='verify_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='otp_digit',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='verify_status',
            field=models.BooleanField(default=False),
        ),
    ]
