# Generated by Django 4.0.6 on 2022-08-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_student_otp_digit_student_verify_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic',
            field=models.ImageField(null=True, upload_to='student_profile_imgs/'),
        ),
        migrations.AddField(
            model_name='student',
            name='academic_level',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='country',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='english_language',
            field=models.ImageField(null=True, upload_to='student_profile_imgs/'),
        ),
    ]
