# Generated by Django 4.0.6 on 2022-08-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_student_academic_alter_student_academic_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='country',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
