# Generated by Django 4.0.6 on 2022-08-11 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_teacher_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='academic',
        ),
        migrations.RemoveField(
            model_name='student',
            name='academic_level',
        ),
        migrations.RemoveField(
            model_name='student',
            name='country',
        ),
        migrations.RemoveField(
            model_name='student',
            name='english_language',
        ),
        migrations.RemoveField(
            model_name='student',
            name='profile_img',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='country',
        ),
    ]
