# Generated by Django 4.0.6 on 2022-08-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_remove_student_academic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic',
            field=models.FileField(null=True, upload_to='student_document/'),
        ),
        migrations.AddField(
            model_name='student',
            name='academic_level',
            field=models.FileField(null=True, upload_to='student_document/'),
        ),
        migrations.AddField(
            model_name='student',
            name='country',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='english_language',
            field=models.FileField(null=True, upload_to='student_document/'),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='student_profile_imgs/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='country',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
