# Generated by Django 4.0.6 on 2022-08-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_student_academic_student_academic_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='others',
            field=models.FileField(null=True, upload_to='student_document/'),
        ),
    ]
