# Generated by Django 4.0.6 on 2022-08-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_course_duration_course_intake_course_studymode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='section',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
