# Generated by Django 4.0.6 on 2022-08-11 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_course_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='section',
            new_name='type',
        ),
    ]
