# Generated by Django 4.0.6 on 2022-08-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_rename_section_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='schooldescription',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
