# Generated by Django 4.0.6 on 2022-08-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_course_schooldescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='document1',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='document2',
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='document3',
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='document4',
            field=models.CharField(default=3, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='document5',
            field=models.CharField(default=3, max_length=150),
            preserve_default=False,
        ),
    ]
