# Generated by Django 4.0.6 on 2022-08-11 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_course_document1_course_document2_course_document3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='document2',
            new_name='docu2',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='document3',
            new_name='docum3',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='document4',
            new_name='docume4',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='document5',
            new_name='documen5',
        ),
    ]
