# Generated by Django 4.0.6 on 2022-08-11 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_rename_document2_course_docu2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='docu2',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='docum3',
            new_name='english',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='docume4',
            new_name='hope',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='documen5',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='document1',
            new_name='okay',
        ),
    ]
