# Generated by Django 4.0.6 on 2022-08-12 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_rename_docu2_course_document_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='document',
            new_name='document1',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='english',
            new_name='document2',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='hope',
            new_name='document3',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='language',
            new_name='document4',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='okay',
            new_name='document5',
        ),
    ]
