# Generated by Django 4.0.6 on 2022-08-12 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_rename_document_course_document1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='document1',
            new_name='document',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='document2',
            new_name='english',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='document3',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='document4',
            new_name='tops',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='document5',
            new_name='ups',
        ),
    ]
