# Generated by Django 4.0.6 on 2022-08-12 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_rename_document1_course_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='document',
        ),
        migrations.RemoveField(
            model_name='course',
            name='english',
        ),
        migrations.RemoveField(
            model_name='course',
            name='language',
        ),
        migrations.RemoveField(
            model_name='course',
            name='tops',
        ),
        migrations.RemoveField(
            model_name='course',
            name='ups',
        ),
    ]
