# Generated by Django 4.0.6 on 2022-08-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_remove_course_document_remove_course_english_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='bird',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='chick',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='eagle',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='fowl',
            field=models.CharField(default=3, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='table',
            field=models.CharField(default=3, max_length=200),
            preserve_default=False,
        ),
    ]
