# Generated by Django 4.0.6 on 2022-08-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_remove_teacher_bird_remove_teacher_chick_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='deadline',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
