# Generated by Django 4.0.6 on 2022-08-13 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_remove_replycontact_add_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='replycontact',
            options={'verbose_name_plural': '9. ReplyContact'},
        ),
    ]
