# Generated by Django 4.0.6 on 2022-08-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_teacher_mobile_no_alter_student_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='mobile_no',
        ),
        migrations.AlterField(
            model_name='student',
            name='country',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='teacher_profile_imgs/'),
        ),
        migrations.DeleteModel(
            name='TeacherStudentChat',
        ),
    ]
