# Generated by Django 4.0.6 on 2022-08-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_remove_teacher_mobile_no_alter_student_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='query',
            new_name='query_txt',
        ),
        migrations.AddField(
            model_name='teacher',
            name='mobile_no',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
