# Generated by Django 4.0.6 on 2022-08-15 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_rename_query_contact_query_txt_teacher_mobile_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='mobile_no',
        ),
    ]
