# Generated by Django 4.0.6 on 2022-08-15 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_remove_course_mobile_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReplyContact',
        ),
    ]
