# Generated by Django 4.0.6 on 2022-08-15 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_delete_replycontact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='query_txt',
            new_name='query',
        ),
    ]
