# Generated by Django 4.0.6 on 2022-08-15 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_rename_query_txt_contact_query'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='mobile_no',
            new_name='mobile',
        ),
    ]
