# Generated by Django 4.0.6 on 2022-08-15 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_rename_mobile_no_teacher_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='mobile',
            new_name='mobile_no',
        ),
    ]
