# Generated by Django 4.0.6 on 2022-08-15 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_rename_mobile_teacher_mobile_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='country',
            new_name='countrys',
        ),
    ]
